name: Android UI Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ui-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        suite: [
          PaymentTests,
          CatalogPageTests,
          GuestCartTests,

          ReviewOrderTests,
          LoginTests,
          LogoutTests,

          GuestCheckoutFlowTests,
          ProductDetailsPageTests,
          OrderCompletePageTests,

          LoggedInUserCheckoutFlowTests,
          LoggedInUserCartTests,
          CheckoutTests
        ]
      max-parallel: 3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Node & Appium
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs npm
          npm install -g appium
          appium driver install uiautomator2

      - name: Enable KVM
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run tests on emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 34
          target: google_apis
          arch: x86_64
          profile: pixel_7
          emulator-options: -no-snapshot -noaudio -no-window -no-boot-anim -gpu swiftshader_indirect
          disable-animations: true
          script: |
            nohup adb logcat > logcat.log 2>&1 &
            nohup appium > appium.log 2>&1 &
            sleep 10
            mvn -B -Dtest=${{ matrix.suite }} test

      - name: Upload ExtentReport
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: extent-report-${{ matrix.suite }}
          path: Reports/TestReport.html

      - name: Upload screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: screenshots-${{ matrix.suite }}
          path: Reports/screenshots/

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: logs-${{ matrix.suite }}
          path: |
            appium.log
            logcat.log

  merge-reports:
    runs-on: ubuntu-latest
    needs: ui-tests

    steps:
      - name: Download all ExtentReports
        uses: actions/download-artifact@v4
        with:
          path: merged-reports

      - name: Merge ExtentReports
        run: |
          mkdir final
          npm install -g extent-merge
          extent-merge merged-reports final/CombinedReport.html

      - name: Upload merged report
        uses: actions/upload-artifact@v4
        with:
          name: Combined-ExtentReport
          path: final/CombinedReport.html